<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/09/06 15:48:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_db',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
